server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8083
  servlet:
    context-path: /

spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/testshiro?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources:
            static-locations: classpath:/static/,classpath:/templates/pages/
    thymeleaf:
            suffix: .html
            prefix: classpath:/templates/pages/
            mode: HTML5
            encoding: UTF-8
            cache: false
mybatis-plus:
  mapper-locations: classpath*:mappers/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.example.demo.pojo

